### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Sabbir897** [sta-c0000/tpconf_bin_xml#15]
``python3 tpconf_bin_xml.py conf.bin conf.hml
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/tpconf_bin_xml.py", line 28, in <module>
    from Crypto.Cipher import DES   # apt install python3-crypto (OR pip install pycryptodome ?)
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/Crypto/Cipher/__init__.py", line 27, in <module>
    from Crypto.Cipher._mode_ecb import _create_ecb_cipher
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/Crypto/Cipher/_mode_ecb.py", line 29, in <module>
    from Crypto.Util._raw_api import (load_pycryptodome_raw_lib,
  File "/data/data/com.termux/files/usr/lib/python3.9/site-packages/Crypto/Util/_raw_api.py", line 33, in <module>
    from Crypto.Util.py3compat import byte_string
ImportError: cannot import name 'byte_string' from 'Crypto.Util.py3compat' (/data/data/com.termux/files/usr/lib/python3.9/site-packages/Crypto/Util/py3compat.py)

**Comment by sta-c0000** [comment]
Perhaps you have two conflicting crypto libraries installed at the same time? (see [pycrypto issue# 297](https://github.com/pycrypto/pycrypto/issues/297))
Probably should only have one installed: `apt install python3-crypto` OR `apt install python3-pycryptodome`, not both.
